id: ID7DFAE7D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:55:01+00:00'
last_modified: '2022-06-08T13:30:49.492064+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12765
  title: གསུང་ཐོར་བུ། ཐོགས་མེད་བཟང་པོ་དཔལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC9B:
      image_group_id: I1KG17029
      title: ''
      total_pages: 386
      order: 1
      base_file: CC9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
