id: P010425
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:15.523871
source_metadata:
  id: bdr:W1KG12765
  title: གསུང་ཐོར་བུ། ཐོགས་མེད་བཟང་པོ་དཔལ།
  author: ''
  volumes:
    20f8866e433b490f97154b32ed3d94b3:
      image_group_id: I1KG17029
      title: ''
      volume_number: 1
      total_pages: 386
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
